'use client';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { useForm } from 'react-hook-form';
import { z } from 'zod';
import { zodResolver } from '@hookform/resolvers/zod';
import { register as registerUser } from '@/lib/api/auth';
import { Button } from '@/components/ui/Button'; import { Input } from '@/components/ui/Input'; import { Select } from '@/components/ui/Select'; import { Card } from '@/components/ui/Card';
const schema = z.object({ email: z.string().email().max(254), password: z.string().min(10).max(64).regex(/[A-Za-z]/).regex(/\d/), firstName: z.string().min(1).max(60), lastName: z.string().min(1).max(60), handle: z.string().min(3).max(30).regex(/^[a-z0-9_]+$/), role: z.enum(['JOB_SEEKER','RECRUITER']) }); type Form = z.infer<typeof schema>;
export default function RegisterPage() { const router = useRouter(); const [error, setError] = useState(''); const { register, handleSubmit, formState: { errors, isSubmitting } } = useForm<Form>({ resolver: zodResolver(schema), defaultValues: { role: 'JOB_SEEKER' } }); return <div className="mx-auto max-w-lg px-4 py-12"><Card><h1 className="text-2xl font-black">Create your JobForge account</h1><form className="mt-6 grid gap-4 sm:grid-cols-2" onSubmit={handleSubmit(async (v) => { try { await registerUser(v); router.push('/login'); } catch { setError('Registration failed. Check your details and try again.'); } })}>{(['firstName','lastName','handle','email'] as const).map((name) => <div key={name} className="sm:col-span-1"><label className="mb-1 block text-sm font-semibold">{name}</label><Input {...register(name)} />{errors[name] && <p className="text-xs text-red-600">{errors[name]?.message}</p>}</div>)}<div><label className="mb-1 block text-sm font-semibold">Password</label><Input type="password" {...register('password')} />{errors.password && <p className="text-xs text-red-600">{errors.password.message}</p>}</div><div><label className="mb-1 block text-sm font-semibold">Account type</label><Select {...register('role')}><option value="JOB_SEEKER">Job seeker</option><option value="RECRUITER">Recruiter</option></Select></div>{error && <p role="alert" className="sm:col-span-2 text-sm text-red-600">{error}</p>}<div className="sm:col-span-2"><Button disabled={isSubmitting} className="w-full">Create account</Button></div></form></Card></div>; }
