'use client';
import Link from 'next/link';
import { useParams } from 'next/navigation';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { getApplication, rateApplication } from '@/lib/api/applications';
import { Card } from '@/components/ui/Card';
import { StatusBadge } from '@/components/applications/StatusBadge';
import { RecruiterStatusActions } from '@/features/applications/ApplicationActions';
import { ApplicationNotes } from '@/features/applications/ApplicationNotes';
import { ApplicationInterviewsPanel } from '@/features/interviews/ApplicationInterviewsPanel';
import { useState } from 'react';
import { ApiClientError } from '@/lib/api/client';
export default function RecruiterApplicationDetailPage(){const {id}=useParams<{id:string}>();const qc=useQueryClient();const q=useQuery({queryKey:['application',id],queryFn:()=>getApplication(id),enabled:Boolean(id)});const [rating,setRating]=useState(0);const [error,setError]=useState('');if(q.isLoading)return <main className="mx-auto max-w-4xl px-4 py-10">Loading application…</main>;if(q.error||!q.data)return <main className="mx-auto max-w-4xl px-4 py-10" role="alert">Application not found or unavailable.</main>;const a=q.data;return <main className="mx-auto max-w-4xl px-4 py-10"><Card><div className="flex flex-col justify-between gap-4 md:flex-row"><div><p className="text-sm text-slate-500">Candidate</p><h1 className="text-2xl font-black">{a.seeker?.firstName} {a.seeker?.lastName}</h1><p className="text-slate-600">{a.profileSnapshot?.headline??'Candidate profile'}</p><Link href={`/jobs/${a.job.id}`} className="mt-2 inline-block text-sm font-semibold underline">{a.job.title}</Link></div><StatusBadge status={a.status}/></div><div className="mt-6"><RecruiterStatusActions application={a} onUpdated={next=>qc.setQueryData(['application',id],next)}/></div><section className="mt-8"><h2 className="text-lg font-bold">Profile snapshot</h2><p className="mt-2 text-sm text-slate-700">Skills: {a.profileSnapshot?.skills.join(', ')||'—'}</p><p className="mt-1 text-sm text-slate-700">Experience: {a.profileSnapshot?.yearsExperience??'—'} years</p></section><section className="mt-8"><h2 className="text-lg font-bold">Rating</h2><div className="mt-2 flex flex-wrap gap-2">{[1,2,3,4,5].map(n=><button key={n} type="button" aria-label={`Rate ${n} out of 5`} onClick={()=>setRating(n)} className={`rounded border px-3 py-2 ${n<=(rating||a.rating||0)?'bg-slate-900 text-white':''}`}>★ {n}</button>)}<button className="rounded bg-slate-900 px-3 py-2 text-sm font-semibold text-white" disabled={!rating} onClick={async()=>{try{const next=await rateApplication(a.id,rating);qc.setQueryData(['application',id],next);setError('')}catch(e){setError(e instanceof ApiClientError?e.message:'Unable to save rating.')}}}>Save rating</button></div>{error&&<p role="alert" className="mt-2 text-sm text-red-600">{error}</p>}</section><ApplicationInterviewsPanel applicationId={a.id} status={a.status}/><section className="mt-8"><h2 className="text-lg font-bold">Status history</h2><ol className="mt-3 space-y-2">{a.statusHistory.map((h,i)=><li key={`${h.at}-${i}`} className="rounded-lg bg-slate-50 p-3 text-sm"><b>{h.to.replaceAll('_',' ')}</b> · {new Date(h.at).toLocaleString()}{h.reason?` · ${h.reason}`:''}</li>)}</ol></section></Card><ApplicationNotes applicationId={a.id}/></main>}
